- defaults:
    link:
      create: true
      relink: true
- clean: ['~', '~/.config']
- link:
    ~/.zsh:
    ~/.zshrc:
    ~/.tmux.conf:
    ~/.config/terminator:
- shell:
  - ["git submodule update --init --recursive", "Installing submodules"]
